// <auto-generated />
namespace NCCRD.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201804021300_UpdatedModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201804021300_UpdatedModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201804021101217_201804021300_UpdatedModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
