
//Details
export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const LOAD_PROJECT_DETAILS = "LOAD_PROJECT_DETAILS";
export const LOAD_ADAPTATION_DETAILS = "LOAD_ADAPTATION_DETAILS";
export const LOAD_MITIGATION_DETAILS = "LOAD_MITIGATION_DETAILS";
export const LOAD_MITIGATION_EMISSIONS = "LOAD_MITIGATION_EMISSIONS";
export const LOAD_RESEARCH_DETAILS = "LOAD_RESEARCH_DETAILS";

//Lookups
export const LOAD_PROJECT_TYPE = "LOAD_PROJECT_TYPE";
export const LOAD_PROJECT_SUBTYPE = "LOAD_PROJECT_SUBTYPE";
export const LOAD_PROJECT_STATUS = "LOAD_PROJECT_STATUS";
export const LOAD_USERS = "LOAD_USERS";
export const LOAD_VALIDATION_STATUS = "LOAD_VALIDATION_STATUS";
export const LOAD_MA_OPTIONS = "LOAD_MA_OPTIONS";
export const LOAD_ADAPTATION_PURPOSE = "LOAD_ADAPTATION_PURPOSE";
export const LOAD_SECTOR = "LOAD_SECTOR";
export const LOAD_CARBON_CREDIT = "LOAD_CARBON_CREDIT";
export const LOAD_CARBON_CREDIT_MARKET = "LOAD_CARBON_CREDIT_MARKET";
export const LOAD_CDM_STATUS = "LOAD_CDM_STATUS";
export const LOAD_CDM_METHODOLOGY = "LOAD_CDM_METHODOLOGY";
export const LOAD_VOLUNTARY_METHODOLOGY = "LOAD_VOLUNTARY_METHODOLOGY";
export const LOAD_VOLUNTARY_GOLD_STANDARD = "LOAD_VOLUNTARY_GOLD_STANDARD";
export const LOAD_RESEARCH_TYPE = "LOAD_RESEARCH_TYPE";
export const LOAD_TARGET_AUDIENCE = "LOAD_TARGET_AUDIENCE";
export const LOAD_TYPOLOGY = "LOAD_TYPOLOGY";

//Filters
export const LOAD_TITLE_FILTER = "LOAD_TITLE_FILTER";
export const LOAD_STATUS_FILTER = "LOAD_STATUS_FILTER";
export const LOAD_TYPOLOGY_FILTER = "LOAD_TYPOLOGY_FILTER";
export const LOAD_REGION_FILTER = "LOAD_REGION_FILTER";
export const LOAD_SECTOR_FILTER = "LOAD_SECTOR_FILTER";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

//Trees
export const LOAD_REGION_TREE = "LOAD_REGION_TREE";
export const LOAD_SECTOR_TREE = "LOAD_SECTOR_TREE";

//Loading
export const SET_LOADING = "SET_LOADING";