
export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const LOAD_REGIONS = "LOAD_PROJECT_STATUS";
export const LOAD_TYPOLOGY = "LOAD_TYPOLOGY";
export const LOAD_REGION_TREE = "LOAD_REGION_TREE";
export const LOAD_SECTOR_TREE = "LOAD_SECTOR_TREE";