
//Details
export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const LOAD_PROJECT_DETAILS = "LOAD_PROJECT_DETAILS";
export const LOAD_ADAPTATION_DETAILS = "LOAD_ADAPTATION_DETAILS";
export const ADD_ADAPTATION_DETAILS = "ADD_ADAPTATION_DETAILS";
export const LOAD_MITIGATION_DETAILS = "LOAD_MITIGATION_DETAILS";
export const ADD_MITIGATION_DETAILS = "ADD_MITIGATION_DETAILS";
export const LOAD_MITIGATION_EMISSIONS = "LOAD_MITIGATION_EMISSIONS";
export const LOAD_RESEARCH_DETAILS = "LOAD_RESEARCH_DETAILS";
export const SET_EDIT_MODE = "SET_EDIT_MODE";
export const SET_PROJECT_DETAILS_YEAR_FROM = "SET_PROJECT_DETAILS_YEAR_FROM";
export const SET_PROJECT_DETAILS_YEAR_TO = "SET_PROJECT_DETAILS_YEAR_TO";
export const SET_PROJECT_DETAILS_BUDGET_FROM = "SET_PROJECT_DETAILS_BUDGET_FROM";
export const SET_PROJECT_DETAILS_BUDGET_TO = "SET_PROJECT_DETAILS_BUDGET_TO";
export const SET_PROJECT_DETAILS_DESCRIPTION = "SET_PROJECT_DETAILS_DESCRIPTION";
export const SET_PROJECT_DETAILS_LEAD_AGENT = "SET_PROJECT_DETAILS_LEAD_AGENT";
export const SET_PROJECT_DETAILS_HOST_PARTNER = "SET_PROJECT_DETAILS_HOST_PARTNER";
export const SET_PROJECT_DETAILS_HOST_ORG = "SET_PROJECT_DETAILS_HOST_ORG";
export const SET_PROJECT_DETAILS_ALT_CONTACT = "SET_PROJECT_DETAILS_ALT_CONTACT";
export const SET_PROJECT_DETAILS_ALT_CONTACT_EMAIL = "SET_PROJECT_DETAILS_ALT_CONTACT_EMAIL";
export const SET_PROJECT_DETAILS_LINK = "SET_PROJECT_DETAILS_LINK";
export const SET_PROJECT_DETAILS_VALIDATION_COMMENTS = "SET_PROJECT_DETAILS_VALIDATION_COMMENTS";
export const SET_PROJECT_DETAILS_PROJECT_TYPE = "SET_PROJECT_DETAILS_PROJECT_TYPE";
export const SET_PROJECT_DETAILS_PROJECT_SUBTYPE = "SET_PROJECT_DETAILS_PROJECT_SUBTYPE";
export const SET_PROJECT_DETAILS_PROJECT_STATUS = "SET_PROJECT_DETAILS_PROJECT_STATUS";
export const SET_PROJECT_DETAILS_PROJECT_MANAGER = "SET_PROJECT_DETAILS_PROJECT_MANAGER";
export const SET_PROJECT_DETAILS_VALIDATION_STATUS = "SET_PROJECT_DETAILS_VALIDATION_STATUS";
export const SET_PROJECT_DETAILS_MAOPTION = "SET_PROJECT_DETAILS_MAOPTION";
export const SET_ADAPTATION_DETAILS_DESCR = "SET_ADAPTATION_DETAILS_DESCR";
export const SET_ADAPTATION_DETAILS_PURPOSE = "SET_ADAPTATION_DETAILS_PURPOSE";
export const SET_ADAPTATION_DETAILS_SECTOR = "SET_ADAPTATION_DETAILS_SECTOR";
export const SET_MITIGATION_CARBON_CREDIT = "SET_MITIGATION_CARBON_CREDIT";
export const SET_MITIGATION_CARBON_CREDIT_MARKET = "SET_MITIGATION_CARBON_CREDIT_MARKET";
export const SET_MITIGATION_CDM_STATUS = "SET_MITIGATION_CDM_STATUS";
export const SET_MITIGATION_CDM_METHODOLOGY = "SET_MITIGATION_CDM_METHODOLOGY";
export const SET_MITIGATION_VOLUNTARY_METHODOLOGY = "SET_MITIGATION_VOLUNTARY_METHODOLOGY";
export const SET_MITIGATION_VOLUNTARY_GOLD_STANDARD = "SET_MITIGATION_VOLUNTARY_GOLD_STANDARD";
export const SET_MITIGATION_CDM_PROJECT_NUMBER = "SET_MITIGATION_CDM_PROJECT_NUMBER";
export const SET_MITIGATION_OTHER_DESCR = "SET_MITIGATION_OTHER_DESCR";
export const SET_MITIGATION_SECTOR = "SET_MITIGATION_SECTOR";

//Lookups
export const LOAD_PROJECT_TYPE = "LOAD_PROJECT_TYPE";
export const LOAD_PROJECT_SUBTYPE = "LOAD_PROJECT_SUBTYPE";
export const LOAD_PROJECT_STATUS = "LOAD_PROJECT_STATUS";
export const LOAD_USERS = "LOAD_USERS";
export const LOAD_VALIDATION_STATUS = "LOAD_VALIDATION_STATUS";
export const LOAD_MA_OPTIONS = "LOAD_MA_OPTIONS";
export const LOAD_ADAPTATION_PURPOSE = "LOAD_ADAPTATION_PURPOSE";
export const LOAD_SECTOR = "LOAD_SECTOR";
export const LOAD_CARBON_CREDIT = "LOAD_CARBON_CREDIT";
export const LOAD_CARBON_CREDIT_MARKET = "LOAD_CARBON_CREDIT_MARKET";
export const LOAD_CDM_STATUS = "LOAD_CDM_STATUS";
export const LOAD_CDM_METHODOLOGY = "LOAD_CDM_METHODOLOGY";
export const LOAD_VOLUNTARY_METHODOLOGY = "LOAD_VOLUNTARY_METHODOLOGY";
export const LOAD_VOLUNTARY_GOLD_STANDARD = "LOAD_VOLUNTARY_GOLD_STANDARD";
export const LOAD_RESEARCH_TYPE = "LOAD_RESEARCH_TYPE";
export const LOAD_TARGET_AUDIENCE = "LOAD_TARGET_AUDIENCE";
export const LOAD_TYPOLOGY = "LOAD_TYPOLOGY";

//Filters
export const LOAD_TITLE_FILTER = "LOAD_TITLE_FILTER";
export const LOAD_STATUS_FILTER = "LOAD_STATUS_FILTER";
export const LOAD_TYPOLOGY_FILTER = "LOAD_TYPOLOGY_FILTER";
export const LOAD_REGION_FILTER = "LOAD_REGION_FILTER";
export const LOAD_SECTOR_FILTER = "LOAD_SECTOR_FILTER";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

//Trees
export const LOAD_REGION_TREE = "LOAD_REGION_TREE";
export const LOAD_SECTOR_TREE = "LOAD_SECTOR_TREE";

//Loading
export const SET_LOADING = "SET_LOADING";