DECLARE @RegionMapping TABLE 
(
	[OldRegionId] [int] NOT NULL,
	[NewRegionId] [int] NOT NULL
)

INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (10, 51)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (12, 52)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (13, 110)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (15, 50)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (16, 11)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (17, 61)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (18, 33)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (19, 53)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (20, 32)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (21, 12)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (22, 15)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (23, 10)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (24, 202)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (26, 19)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (28, 57)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (29, 80)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (30, 25)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (31, 16)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (32, 44)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (34, 56)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (35, 17)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (36, 47)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (37, 55)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (38, 38)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (39, 26)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (40, 42)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (41, 31)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (42, 97)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (44, 84)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (45, 81)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (49, 24)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (50, 41)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (51, 13)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (52, 39)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (54, 60)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (55, 45)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (57, 48)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (59, 163)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (59, 37)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (60, 29)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (61, 59)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (64, 242)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (65, 150)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (68, 76)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (69, 82)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (70, 260)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (71, 241)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (72, 227)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (73, 104)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (74, 169)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (75, 138)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (79, 123)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (80, 238)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (81, 102)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (81, 103)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (83, 230)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (86, 157)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (88, 246)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (89, 95)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (91, 72)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (93, 120)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (94, 65)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (95, 204)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (97, 135)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (98, 261)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (100, 180)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (102, 220)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (104, 184)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (106, 239)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (108, 77)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (110, 196)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (112, 258)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (113, 143)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (118, 69)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (120, 217)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (123, 271)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (124, 183)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (125, 87)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (128, 163)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (130, 197)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (131, 144)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (132, 270)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (133, 116)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (134, 158)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (136, 153)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (138, 83)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (144, 190)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (145, 71)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (146, 67)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (147, 252)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (148, 250)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (149, 233)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (150, 224)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (155, 274)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (156, 140)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (157, 174)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (159, 113)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (161, 199)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (162, 146)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (164, 247)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (166, 231)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (167, 175)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (168, 114)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (169, 141)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (171, 117)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (172, 167)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (175, 148)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (178, 83)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (181, 216)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (190, 168)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (191, 122)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (192, 96)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (198, 105)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (202, 93)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (208, 78)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (213, 139)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (214, 64)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (217, 73)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (221, 106)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (227, 112)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (228, 119)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (230, 171)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (235, 55)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (237, 125)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (238, 206)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (239, 262)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (242, 132)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (251, 255)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (260, 129)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (262, 91)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (265, 166)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (267, 86)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (275, 145)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (278, 267)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (279, 256)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (280, 162)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (289, 221)
INSERT @RegionMapping ([OldRegionId], [NewRegionId]) VALUES (292, 91)
	
update
	PR
set
	PR.RegionId = RM.NewRegionId
from
	NCCRD_TEST.dbo.ProjectRegion PR
inner join
	@RegionMapping RM
	ON PR.RegionId = RM.OldRegionId